sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  redis:
    host: localhost
    port: 6379
    password: 123
    database: 10
  wechat:
    appid: wxb401fa14d7567036
    secret: 10fd5727e6f4c260e9765c6e346d0aeb